---
- name: Demonstrate operating on MAAS Node Scripts
  hosts: all
  gather_facts: false
  module_defaults:
    rhc.maas_settings.maas_node_scripts:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Grab the A version of the script
      ansible.builtin.file:
        path: "{{ playbook_dir }}/files/script1.sh"
        src: "{{ playbook_dir }}/files/script1a.sh"
        state: hard
        force: true
      delegate_to: localhost

    - name: Remove all node scripts
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: []
        state: exact
      delegate_to: localhost

    - name: Add a Node Script
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
      delegate_to: localhost
      vars:
        user_scripts:
          - name: script1
            file: script1.sh

    - name: Add multiple scripts
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
      delegate_to: localhost
      vars:
        user_scripts:
          - name: script1
            file: script1.sh
          - name: script2
            file: script2.sh

    - name: Grab the B version script1
      ansible.builtin.file:
        path: "{{ playbook_dir }}/files/script1.sh"
        src: "{{ playbook_dir }}/files/script1b.sh"
        state: hard
        force: true
      delegate_to: localhost

    - name: Add the B version of script1
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
      delegate_to: localhost
      vars:
        user_scripts:
          - name: script1
            file: script1.sh

    - name: Set exact scripts
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
        state: exact
      delegate_to: localhost
      vars:
        user_scripts:
          - name: script2
            file: script2.sh

    - name: Remove given scripts
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
        state: absent
      delegate_to: localhost
      vars:
        user_scripts:
          - name: script1
            file: script1.sh
          - name: script2
            file: script2.sh

    - name: Add a script which has no local file
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        user_scripts:
          - name: no_such_script
            file: scriptfoo

    - name: Add a script which has an invalid name
      rhc.maas_settings.maas_node_scripts:
        script_dir: /root/user_scripts/
        user_scripts: "{{ user_scripts }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        user_scripts:
          - name: Script 2
            file: script2.sh
