---
- name: Demonstrate operating on MAAS Subnets
  hosts: all
  gather_facts: false
  module_defaults:
    rhc.maas_settings.maas_subnets:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add a subnet
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      vars:
        subnets:
          - name: Test192
            description: Test 192.168 network
            cidr: 192.168.66.0/24
            gateway_ip: 192.168.66.1

    - name: Add another subnet
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      vars:
        subnets:
          - name: Test192.67
            description: Test 192.168.67 network
            cidr: 192.168.67.0/24
            gateway_ip: 192.168.67.1

    - name: Add DNS servers to a subnet
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      vars:
        subnets:
          - name: Test192
            description: Test 192.168 network
            cidr: 192.168.66.0/24
            dns_servers:
              - 10.66.0.5
              - 10.66.0.6
            gateway_ip: 192.168.66.1

    - name: Remove DNS servers from a subnet
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      vars:
        subnets:
          - name: Test192
            description: Test 192.168 network
            cidr: 192.168.66.0/24
            gateway_ip: 192.168.66.1

    - name: Remove a subnet
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
        state: absent
      delegate_to: localhost
      vars:
        subnets:
          - cidr: 192.168.67.0/24

    - name: Remove all subnets
      rhc.maas_settings.maas_subnets:
        subnets: []
        state: exact
      delegate_to: localhost

    - name: Reset to original state using exact state
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
        state: exact
      delegate_to: localhost
      vars:
        subnets:
          - cidr: 10.66.0.0/16
            gateway_ip: 10.66.0.1
            name: 10.66.0.0/16
          - cidr: 192.168.66.0/24
            gateway_ip: 192.168.66.1
            name: Test192
            description: Test 192.168 network

    - name: Try to add subnet with no CIDR
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - name: 192.168.256.0/24

    - name: Try to add invalid CIDR
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - cidr: 192.168.256.0/24

    - name: Try to add invalid DNS
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - cidr: 192.168.255.0/24
            dns_servers:
              - 10.66.0.5
              - 10.256.1.2

    - name: Try to add invalid gateway_ip (not an IP)
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - cidr: 192.168.255.0/24
            gateway_ip: 192.167.255.1

    - name: Try to add invalid gateway_ip (not in cidr)
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - cidr: 192.168.255.0/24
            gateway_ip: 192.167.255.1

    - name: Try to add invalid vid
      rhc.maas_settings.maas_subnets:
        subnets: "{{ subnets }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        subnets:
          - cidr: 192.168.255.0/24
            gateway_ip: 192.168.255.1
            vid: invalid_vid
