---
- name: Demonstrate operating on MAAS Static Routes
  hosts: all
  gather_facts: false
  module_defaults:
    rhc.maas_settings.maas_static_routes:
      username: "{{ maas_username | default(omit) }}"
      password: "{{ maas_password | default(omit) }}"
      token: "{{ maas_token | default(omit) }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add a static route
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1

    - name: Add same route with a non-default metric
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1
            metric: 1

    - name: Add again with no metric defined (should change back)
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1

    - name: Add again
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1

    - name: Remove static routes (some existing, some not)
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: absent
      delegate_to: localhost
      vars:
        static_routes:
          - destination: 192.168.66.0/24
          - destination: 2.0.0.0/8

    - name: Exact static
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1
            metric: 1

    - name: Exact static (empty list)
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      vars:
        static_routes: []

    - name: Try invalid source
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      ignore_errors: true
      vars:
        static_routes:
          - source: 10.66.256.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.0.1
            metric: 1

    - name: Try invalid dest
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      ignore_errors: true
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.266.0/24
            gateway_ip: 10.66.0.1
            metric: 1

    - name: Try invalid gateway_ip (not an IP)
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      ignore_errors: true
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.66.01
            metric: 1

    - name: Try invalid gateway_ip (not in source network)
      rhc.maas_settings.maas_static_routes:
        static_routes: "{{ static_routes }}"
        state: exact
      delegate_to: localhost
      ignore_errors: true
      vars:
        static_routes:
          - source: 10.66.0.0/16
            destination: 192.168.66.0/24
            gateway_ip: 10.67.0.1
            metric: 1
