---
- name: Demonstrate operating on MAAS tags
  hosts: all
  gather_facts: false
  module_defaults:
    rhc.maas_settings.maas_tags:
      username: "{{ maas_username | default(omit) }}"
      password: "{{ maas_password | default(omit) }}"
      token: "{{ maas_token | default(omit) }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add some tags
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
          - name: virtual
    - name: Modify a tag
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
            comment: This is the first tag
    - name: Remove a tag
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
        state: absent
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
    - name: Exact List
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags:
          - name: first_tag
          - name: virtual
    - name: Exact List with changes
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags:
          - name: virtual
    - name: Exact List with no members
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
        state: exact
      delegate_to: localhost
      vars:
        maas_tags: []
    - name: Add an invalid tag
      rhc.maas_settings.maas_tags:
        tags: "{{ maas_tags }}"
      delegate_to: localhost
      ignore_errors: true
      vars:
        maas_tags:
          - name: tag with whitespace
