---
- name: Demonstrate operating on MAAS VLANs
  hosts: all
  gather_facts: false
  module_defaults:
    rhc.maas_settings.maas_vlans:
      username: "{{ maas_username }}"
      password: "{{ maas_password }}"
      site: "{{ maas_site }}"
  tasks:
    - name: Add two VLANS
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      delegate_to: localhost
      vars:
        vlans:
          - name: Initial VLAN 100
            vid: 100
          - name: 200

    - name: Modify a vlan
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      delegate_to: localhost
      vars:
        vlans:
          - name: Updated VLAN 100
            vid: 100

    - name: Remove one
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
        state: absent
      delegate_to: localhost
      vars:
        vlans:
          - name: 200

    - name: Set an exact list
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
        state: exact
      delegate_to: localhost
      vars:
        vlans:
          - name: VLAN 400
            vid: 400
          - name: 500

    - name: Set a difference exact list
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
        state: exact
      delegate_to: localhost
      vars:
        vlans:
          - name: 200
          - name: 300
          - name: Renamed VLAN 400
            vid: 400

    - name: Invalid VID
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: vlan100
          - name: vlan4096
            vid: 4096

    - name: Try and add two with the same VID
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 100
          - name: Another VLAN
            vid: 100

    - name: Try and change a VID
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 300
            vid: 301

    - name: Try and use a parameter we don't support
      rhc.maas_settings.maas_vlans:
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 300
            fabric_id: 2

    - name: Try and use an incorrect password
      rhc.maas_settings.maas_vlans:
        password: "{{ maas_password }}+"
        vlans: "{{ vlans }}"
      ignore_errors: true
      delegate_to: localhost
      vars:
        vlans:
          - name: 300
